### PR TITLE
Added free_text field

### PR DESCRIPTION
**Pull request by harabchuk**
Hi Jannis,
First thank you for the django-robots.

I have added one more field free_text for non-standard rules. This allows me to add `host` key to my robots.txt as Yandex.ru suggests. 

If you consider it useful please review and accept my changes.

### CODE REVIEW

**Comment by SalahAdDin** [comment]
Please, put a example :D :+1:

**Comment by harabchuk** [comment]
@SalahAdDin here is an example of non-standard directives
```
User-agent: Yandex
Allow: /
Crawl-delay: 10.0
Clean-param: sessionid /
host: example.com
```

**Comment by SalahAdDin** [comment]
Wow, awesome :D

**Comment by jezdez** [comment]
I'm sorry but this is a non-standard feature and I can't support it. I think you could overwrite the model used by the app right now this is a no-go in the form of the PR.

**Pull request closed without merging**
